/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 *******************************************************************************/
#include "STM32F103_RCC.h"
#include "stm32f103xx_EXTI.h"
#include "infrastructure.h"
#include "Cortex_M3_NVIC.h"
enum CPU_ACCESS_LEVEL {privileged, unprivileged};
void switch_cpu_level(enum CPU_ACCESS_LEVEL level);
int global_var=0;
int main(void)
{
	/*initialization*/
	int i = 0;

	set_bit(EXTI_IMR,0);
	set_bit(NVIC_ISER0,6);
    /* Loop forever */
	for(i=0;i<3;i++)
	{
		if (i==1){
			switch_cpu_level(unprivileged);
		}
		else if ( i==2)
		{
			switch_cpu_level(privileged);
			i = 0 ;

		}
	}
}

void switch_cpu_level(enum CPU_ACCESS_LEVEL level)
{
	switch(level)
	{
	case unprivileged:
		__asm(  "mrs r3,CONTROL \n\t"
				"orr r3,r3,#1	\n\t"
				"msr CONTROL,r3");
		break;
	case privileged:
	{
		global_var = 1;
		set_bit(EXTI_SWIER,0);
		global_var = 0;
		break;
	}
	}
}
void EXTI0_IRQHandler()
{
	set_bit(EXTI_PR,0);
	__asm(  "mrs r3,CONTROL	\n\t"
			"lsr r3,r3,#1	\n\t"
			"lsl r3,r3,#1	\n\t"
			"msr CONTROL,r3");
}
